import shutil
from pathlib import Path

import httpx
from sqlalchemy import select

from media_pilot.adapters.metadata import (
    MetadataCredits,
    MetadataDetail,
    MetadataExternalIds,
    MetadataImages,
)
from media_pilot.config import AppConfig
from media_pilot.orchestration.jellyfin_show_writer import (
    EpisodeTarget,
    _cleanup_show_overwrite_targets,
    build_show_write_plan,
    detect_show_identity_conflict,
    detect_show_write_conflict,
    execute_show_write,
    render_episode_nfo,
    render_season_nfo,
    render_tvshow_nfo,
)
from media_pilot.repository.database import create_session_factory, initialize_database
from media_pilot.repository.models import FileAsset, OperationRecord, WriteResult
from media_pilot.repository.repositories import IngestTaskCreate, IngestTaskRepository


# ── build_show_write_plan ──

def test_build_show_write_plan_uses_jellyfin_show_directory_structure(tmp_path: Path) -> None:
    detail = make_show_detail()
    episodes = [
        EpisodeTarget(
            episode=1, season=1,
            source_file=tmp_path / "Show.Title.S01E01.mkv",
            target_file=Path(""),
        ),
        EpisodeTarget(
            episode=2, season=1,
            source_file=tmp_path / "Show.Title.S01E02.mkv",
            target_file=Path(""),
        ),
    ]
    shows_dir = tmp_path / "shows"

    plan = build_show_write_plan(
        shows_dir=shows_dir,
        episodes=episodes,
        detail=detail,
        task_id="task-1",
    )

    assert plan.show_dir_name == "Example Show (2026)"
    assert plan.season_dir_name == "Season 01"
    assert plan.target_dir == (
        shows_dir / ".media-pilot-staging" / "task-1" / "Example Show (2026)" / "Season 01"
    )
    assert plan.final_target_dir == shows_dir / "Example Show (2026)" / "Season 01"
    assert plan.tvshow_nfo_path == (
        shows_dir / ".media-pilot-staging" / "task-1" / "Example Show (2026)" / "tvshow.nfo"
    )
    assert plan.season_nfo_path == plan.target_dir / "season.nfo"


def test_build_show_write_plan_computes_episode_nfo_paths(tmp_path: Path) -> None:
    detail = make_show_detail()
    episodes = [
        EpisodeTarget(
            episode=3, season=1,
            source_file=tmp_path / "Show.Title.S01E03.mkv",
            target_file=Path(""),
        ),
    ]
    shows_dir = tmp_path / "shows"

    plan = build_show_write_plan(
        shows_dir=shows_dir,
        episodes=episodes,
        detail=detail,
        task_id="task-2",
    )

    assert plan.episode_nfo_paths[3] == (
        plan.target_dir / "Example Show (2026) - S01E03.nfo"
    )


def test_build_show_write_plan_episode_target_files_with_correct_suffix(tmp_path: Path) -> None:
    detail = make_show_detail()
    episodes = [
        EpisodeTarget(
            episode=5, season=2,
            source_file=tmp_path / "Show.S02E05.mp4",
            target_file=Path(""),
        ),
    ]
    shows_dir = tmp_path / "shows"

    plan = build_show_write_plan(
        shows_dir=shows_dir,
        episodes=episodes,
        detail=detail,
        task_id="task-3",
    )

    ep = plan.episodes[0]
    assert ep.episode == 5
    assert ep.season == 2
    assert ep.target_file == (
        plan.target_dir / "Example Show (2026) - S02E05.mp4"
    )
    assert ep.target_file.suffix == ".mp4"


def test_build_show_write_plan_truncates_long_show_title(tmp_path: Path) -> None:
    detail = MetadataDetail(
        **{
            **make_show_detail().__dict__,
            "title": "A Very Long Show Title " * 20,
            "year": 2026,
        }
    )
    episodes = [
        EpisodeTarget(
            episode=1,
            season=1,
            source_file=tmp_path / "Show.S01E01.2160p.WEB-DL.mkv",
            target_file=Path(""),
        ),
    ]

    plan = build_show_write_plan(
        shows_dir=tmp_path / "shows",
        episodes=episodes,
        detail=detail,
        task_id="task-long-show",
    )

    assert plan.show_dir_name.endswith("(2026)")
    assert "..." in plan.show_dir_name
    assert len(plan.show_dir_name.encode("utf-8")) <= 180
    assert len(plan.episodes[0].target_file.name.encode("utf-8")) <= 180
    assert plan.episode_nfo_paths[1] == plan.episodes[0].target_file.with_suffix(".nfo")


# ── render_tvshow_nfo ──

def test_render_tvshow_nfo_includes_media_pilot_signature_and_basic_fields() -> None:
    detail = make_show_detail()

    xml = render_tvshow_nfo(detail)

    assert "<tvshow>" in xml
    assert "Generated by Media Pilot" in xml
    assert "<title>Example Show</title>" in xml
    assert "<originaltitle>Example Original Show</originaltitle>" in xml
    assert "<year>2026</year>" in xml
    assert "<plot>Fake show plot</plot>" in xml
    assert "<premiered>2026-03-01</premiered>" in xml
    assert "<rating>8.2</rating>" in xml
    assert "<source>Media Pilot</source>" in xml


def test_render_tvshow_nfo_includes_ids_taxonomy_and_people() -> None:
    detail = make_show_detail()

    xml = render_tvshow_nfo(detail)

    assert "<genre>Sci-Fi</genre>" in xml
    assert "<country>US</country>" in xml
    assert "<studio>Show Studio</studio>" in xml
    assert "<tmdbid>show:67890</tmdbid>" in xml
    assert "<imdbid>tt2026001</imdbid>" in xml
    assert '<uniqueid type="tmdb" default="true">show:67890</uniqueid>' in xml
    assert '<uniqueid type="imdb" default="false">tt2026001</uniqueid>' in xml
    assert "<director>Show Director</director>" in xml
    assert "<actor>" in xml
    assert "<name>Show Actor</name>" in xml
    assert "<role>Main</role>" in xml
    assert "<thumb>https://example.invalid/show-actor.jpg</thumb>" in xml
    assert "<profile>https://example.invalid/show-actor</profile>" in xml
    assert "<tmdbid>600</tmdbid>" in xml


def test_render_tvshow_nfo_skips_none_values() -> None:
    detail = make_show_detail()
    detail = MetadataDetail(**{**detail.__dict__, "year": None, "rating": None})

    xml = render_tvshow_nfo(detail)

    assert "<year>" not in xml
    assert "<rating>" not in xml


# ── render_season_nfo ──

def test_render_season_nfo_includes_season_number() -> None:
    detail = make_show_detail()
    episodes = [EpisodeTarget(episode=1, season=2, source_file=Path("test.mkv"), target_file=Path(""))]

    xml = render_season_nfo(detail, season_number=2, episodes=episodes)

    assert "<season>" in xml
    assert "Generated by Media Pilot" in xml
    assert "<title>Example Show</title>" in xml
    assert "<seasonnumber>2</seasonnumber>" in xml
    assert "<plot>Fake show plot</plot>" in xml


# ── render_episode_nfo ──

def test_render_episode_nfo_includes_episode_details() -> None:
    detail = make_show_detail()

    xml = render_episode_nfo(detail, season=1, episode=5)

    assert "<episodedetails>" in xml
    assert "Generated by Media Pilot" in xml
    assert "<title>Example Show</title>" in xml
    assert "<showtitle>Example Show</showtitle>" in xml
    assert "<season>1</season>" in xml
    assert "<episode>5</episode>" in xml
    assert "<plot>Fake show plot</plot>" in xml
    assert "<tmdbid>show:67890</tmdbid>" in xml


# ── detect_show_write_conflict ──

def test_detect_show_write_conflict_no_conflict_when_show_dir_alone_exists(
    tmp_path: Path,
) -> None:
    """新语义: 已存在 show 目录但没有 episode 冲突 → 不是 conflict.

    spec: lightweight-media-staging / 剧集发布冲突. show/season 目录
    视为可复用 append 目标, 仅 episode video / NFO / 同源字幕冲突.
    """
    detail = make_show_detail()
    shows_dir = tmp_path / "shows"
    episodes = [
        EpisodeTarget(episode=1, season=1, source_file=tmp_path / "S01E01.mkv", target_file=Path("")),
    ]
    plan = build_show_write_plan(
        shows_dir=shows_dir, episodes=episodes, detail=detail, task_id="task-1",
    )
    (shows_dir / "Example Show (2026)").mkdir(parents=True)

    conflict = detect_show_write_conflict(plan)

    assert conflict is None


def test_detect_show_write_conflict_no_conflict_when_final_season_dir_alone_exists(
    tmp_path: Path,
) -> None:
    """新语义: 已存在 season 目录但没 episode 冲突 → 不是 conflict."""
    detail = make_show_detail()
    shows_dir = tmp_path / "shows"
    episodes = [
        EpisodeTarget(episode=1, season=1, source_file=tmp_path / "S01E01.mkv", target_file=Path("")),
    ]
    plan = build_show_write_plan(
        shows_dir=shows_dir, episodes=episodes, detail=detail, task_id="task-1",
    )
    plan.final_target_dir.parent.mkdir(parents=True, exist_ok=True)
    plan.final_target_dir.mkdir()

    conflict = detect_show_write_conflict(plan)

    assert conflict is None


def test_detect_show_write_conflict_when_target_episode_file_exists(tmp_path: Path) -> None:
    """正向测试: 实际 episode 视频文件已存在 → 仍是 conflict."""
    detail = make_show_detail()
    shows_dir = tmp_path / "shows"
    episodes = [
        EpisodeTarget(episode=1, season=1, source_file=tmp_path / "S01E01.mkv", target_file=Path("")),
    ]
    plan = build_show_write_plan(
        shows_dir=shows_dir, episodes=episodes, detail=detail, task_id="task-1",
    )


def test_detect_show_write_conflict_when_target_episode_file_exists(tmp_path: Path) -> None:
    detail = make_show_detail()
    shows_dir = tmp_path / "shows"
    episodes = [
        EpisodeTarget(episode=1, season=1, source_file=tmp_path / "S01E01.mkv", target_file=Path("")),
    ]
    plan = build_show_write_plan(
        shows_dir=shows_dir, episodes=episodes, detail=detail, task_id="task-1",
    )
    # 新语义: 检查 final target 路径, 不是 staging. 在 final_target_dir
    # 下预先放置同名 episode 文件以触发冲突.
    plan.final_target_dir.mkdir(parents=True)
    final_name = (
        f"{plan.show_dir_name} - S{plan.episodes[0].season:02d}"
        f"E{plan.episodes[0].episode:02d}"
        f"{plan.episodes[0].source_file.suffix}"
    )
    (plan.final_target_dir / final_name).write_bytes(b"existing")

    conflict = detect_show_write_conflict(plan)

    assert conflict == "target_episode_file_exists:S01E01"


def test_detect_show_write_conflict_when_same_stem_subtitle_with_language_suffix_exists(
    tmp_path: Path,
) -> None:
    detail = make_show_detail()
    shows_dir = tmp_path / "shows"
    episodes = [
        EpisodeTarget(episode=1, season=1, source_file=tmp_path / "S01E01.mkv", target_file=Path("")),
    ]
    plan = build_show_write_plan(
        shows_dir=shows_dir, episodes=episodes, detail=detail, task_id="task-1",
    )
    plan.final_target_dir.mkdir(parents=True)
    (
        plan.final_target_dir
        / f"{plan.show_dir_name} - S01E01.chs.srt"
    ).write_text("sub")

    conflict = detect_show_write_conflict(plan)

    assert conflict == "target_episode_subtitle_exists:S01E01"


def test_detect_show_identity_conflict_reads_final_show_root_tvshow_nfo(
    tmp_path: Path,
) -> None:
    detail = make_show_detail()
    shows_dir = tmp_path / "shows"
    episodes = [
        EpisodeTarget(episode=1, season=1, source_file=tmp_path / "S01E01.mkv", target_file=Path("")),
    ]
    plan = build_show_write_plan(
        shows_dir=shows_dir, episodes=episodes, detail=detail, task_id="task-1",
    )
    plan.final_target_dir.parent.mkdir(parents=True, exist_ok=True)
    (plan.final_target_dir.parent / "tvshow.nfo").write_text("<tvshow><tmdbid>other:1</tmdbid></tvshow>")

    conflict = detect_show_identity_conflict(plan, detail)

    assert conflict == "show_identity_mismatch"


def test_detect_show_identity_conflict_allows_same_provider_id(
    tmp_path: Path,
) -> None:
    detail = make_show_detail()
    shows_dir = tmp_path / "shows"
    episodes = [
        EpisodeTarget(episode=1, season=1, source_file=tmp_path / "S01E01.mkv", target_file=Path("")),
    ]
    plan = build_show_write_plan(
        shows_dir=shows_dir, episodes=episodes, detail=detail, task_id="task-1",
    )
    plan.final_target_dir.parent.mkdir(parents=True, exist_ok=True)
    (
        plan.final_target_dir.parent / "tvshow.nfo"
    ).write_text("<tvshow><tmdbid>show:67890</tmdbid></tvshow>")

    conflict = detect_show_identity_conflict(plan, detail)

    assert conflict is None


# ── execute_show_write ──

def test_execute_show_write_reports_progress_steps_in_order(tmp_path: Path) -> None:
    config = make_config(tmp_path)
    session_factory = create_session_factory(config)
    source_path = config.downloads_dir / "Show.Title.S01E01.1080p.mkv"
    source_path.write_bytes(b"episode-bytes")
    detail = make_show_detail()
    detail = MetadataDetail(**{
        **detail.__dict__,
        "images": MetadataImages(
            poster_url="https://img.test/poster.jpg",
            backdrop_url=None,
            logo_url=None,
        ),
    })
    episodes = [
        EpisodeTarget(episode=1, season=1, source_file=source_path, target_file=Path("")),
    ]
    client = make_http_client({
        "https://img.test/poster.jpg": httpx.Response(200, content=b"poster"),
    })
    progress_steps: list[str] = []

    with session_factory() as session:
        task = IngestTaskRepository(session).create(
            IngestTaskCreate(
                source_path=str(source_path),
                status="confirmed",
                current_step="confirmed",
                media_type="show",
            )
        )
        plan = build_show_write_plan(
            shows_dir=config.shows_dir,
            episodes=episodes,
            detail=detail,
            task_id=task.id,
        )

        result = execute_show_write(
            session,
            task_id=task.id,
            detail=detail,
            plan=plan,
            client=client,
            progress_callback=progress_steps.append,
        )
        session.commit()

    assert progress_steps[:3] == [
        "write_show_metadata_assets",
        "copy_episode_S01E01",
        "publish_show_to_library",
    ]
    assert result.status == "warning"  # backdrop/logo URL 为 None 会触发 warning


def test_execute_show_write_produces_tvshow_season_and_episode_nfo(tmp_path: Path) -> None:
    config = make_config(tmp_path)
    session_factory = create_session_factory(config)
    source_path = config.downloads_dir / "Show.Title.S01E03.mkv"
    source_path.write_bytes(b"episode-bytes")
    detail = make_show_detail()
    detail = MetadataDetail(**{
        **detail.__dict__,
        "images": MetadataImages(
            poster_url="https://img.test/poster.jpg",
            backdrop_url=None,
            logo_url=None,
        ),
    })
    episodes = [
        EpisodeTarget(episode=3, season=1, source_file=source_path, target_file=Path("")),
    ]
    client = make_http_client({
        "https://img.test/poster.jpg": httpx.Response(200, content=b"poster"),
    })

    with session_factory() as session:
        task = IngestTaskRepository(session).create(
            IngestTaskCreate(
                source_path=str(source_path),
                status="confirmed",
                current_step="confirmed",
                media_type="show",
            )
        )
        plan = build_show_write_plan(
            shows_dir=config.shows_dir,
            episodes=episodes,
            detail=detail,
            task_id=task.id,
        )

        execute_show_write(
            session,
            task_id=task.id,
            detail=detail,
            plan=plan,
            client=client,
        )
        session.commit()

    # 验证 publish 后 final 目录中的 NFO 文件内容
    final_show_dir = plan.final_target_dir.parent
    tvshow_nfo = (final_show_dir / "tvshow.nfo").read_text()
    assert "<tvshow>" in tvshow_nfo
    assert "<title>Example Show</title>" in tvshow_nfo

    season_nfo = (plan.final_target_dir / "season.nfo").read_text()
    assert "<season>" in season_nfo
    assert "<seasonnumber>1</seasonnumber>" in season_nfo

    ep_nfo_path = plan.final_target_dir / f"{plan.show_dir_name} - S01E03.nfo"
    episode_nfo = ep_nfo_path.read_text()
    assert "<episodedetails>" in episode_nfo
    assert "<season>1</season>" in episode_nfo
    assert "<episode>3</episode>" in episode_nfo

    # 验证 episode 文件存在于 final 目录
    ep = plan.episodes[0]
    final_ep = plan.final_target_dir / ep.target_file.name
    assert final_ep.exists()

    # 验证 final 目录存在
    assert plan.final_target_dir.exists()
    assert plan.final_target_dir.parent.exists()


def test_execute_show_write_poster_download_fails_returns_failed(tmp_path: Path) -> None:
    config = make_config(tmp_path)
    session_factory = create_session_factory(config)
    source_path = config.downloads_dir / "Show.Title.S01E01.mkv"
    source_path.write_bytes(b"episode-bytes")
    detail = make_show_detail()
    detail = MetadataDetail(**{
        **detail.__dict__,
        "images": MetadataImages(
            poster_url="https://img.test/poster.jpg",
            backdrop_url=None,
            logo_url=None,
        ),
    })
    episodes = [
        EpisodeTarget(episode=1, season=1, source_file=source_path, target_file=Path("")),
    ]
    client = make_http_client({
        "https://img.test/poster.jpg": httpx.Response(500, content=b""),
    })

    with session_factory() as session:
        task = IngestTaskRepository(session).create(
            IngestTaskCreate(
                source_path=str(source_path),
                status="confirmed",
                current_step="confirmed",
                media_type="show",
            )
        )
        plan = build_show_write_plan(
            shows_dir=config.shows_dir,
            episodes=episodes,
            detail=detail,
            task_id=task.id,
        )

        result = execute_show_write(
            session, task_id=task.id,
            detail=detail, plan=plan, client=client,
        )
        session.commit()

        write_result = session.scalars(select(WriteResult)).one()

    assert result.status == "failed"
    assert write_result.status == "failed"
    assert write_result.payload["failure_reason"] == "poster_download_failed"


def test_execute_show_write_publish_failure_sets_failed_status(tmp_path: Path, monkeypatch) -> None:
    config = make_config(tmp_path)
    session_factory = create_session_factory(config)
    source_path = config.downloads_dir / "Show.Title.S01E01.mkv"
    source_path.write_bytes(b"episode-bytes")
    detail = make_show_detail()
    detail = MetadataDetail(**{
        **detail.__dict__,
        "images": MetadataImages(
            poster_url="https://img.test/poster.jpg",
            backdrop_url=None,
            logo_url=None,
        ),
    })
    episodes = [
        EpisodeTarget(episode=1, season=1, source_file=source_path, target_file=Path("")),
    ]
    client = make_http_client({
        "https://img.test/poster.jpg": httpx.Response(200, content=b"poster"),
    })

    original_move = shutil.move

    def failing_move(src: str, dst: str):
        if ".media-pilot-staging" in src:
            raise OSError("publish_failed")
        return original_move(src, dst)

    monkeypatch.setattr("media_pilot.orchestration.jellyfin_show_writer.shutil.move", failing_move)

    with session_factory() as session:
        task = IngestTaskRepository(session).create(
            IngestTaskCreate(
                source_path=str(source_path),
                status="confirmed",
                current_step="confirmed",
                media_type="show",
            )
        )
        plan = build_show_write_plan(
            shows_dir=config.shows_dir,
            episodes=episodes,
            detail=detail,
            task_id=task.id,
        )

        result = execute_show_write(
            session, task_id=task.id,
            detail=detail, plan=plan, client=client,
        )
        session.commit()

        write_result = session.scalars(select(WriteResult)).one()

    assert result.status == "failed"
    assert write_result.status == "failed"
    assert write_result.payload["failure_reason"] == "publish_to_library_failed"


def test_execute_show_write_multiple_episodes(tmp_path: Path) -> None:
    config = make_config(tmp_path)
    session_factory = create_session_factory(config)
    ep1_path = config.downloads_dir / "Show.S01E01.mkv"
    ep2_path = config.downloads_dir / "Show.S01E02.mkv"
    ep1_path.write_bytes(b"ep1")
    ep2_path.write_bytes(b"ep2")
    detail = make_show_detail()
    detail = MetadataDetail(**{
        **detail.__dict__,
        "images": MetadataImages(
            poster_url="https://img.test/poster.jpg",
            backdrop_url=None,
            logo_url=None,
        ),
    })
    episodes = [
        EpisodeTarget(episode=1, season=1, source_file=ep1_path, target_file=Path("")),
        EpisodeTarget(episode=2, season=1, source_file=ep2_path, target_file=Path("")),
    ]
    client = make_http_client({
        "https://img.test/poster.jpg": httpx.Response(200, content=b"poster"),
    })
    progress_steps: list[str] = []

    with session_factory() as session:
        task = IngestTaskRepository(session).create(
            IngestTaskCreate(
                source_path=str(ep1_path),
                status="confirmed",
                current_step="confirmed",
                media_type="show",
            )
        )
        plan = build_show_write_plan(
            shows_dir=config.shows_dir,
            episodes=episodes,
            detail=detail,
            task_id=task.id,
        )

        result = execute_show_write(
            session, task_id=task.id,
            detail=detail, plan=plan, client=client,
            progress_callback=progress_steps.append,
        )
        session.commit()

    assert result.status == "warning"  # backdrop/logo URL 为 None 会触发 warning
    # 验证 publish 后 final 目录中的 NFO 文件
    assert (plan.final_target_dir.parent / "tvshow.nfo").exists()
    assert (plan.final_target_dir / "season.nfo").exists()
    assert (plan.final_target_dir / f"{plan.show_dir_name} - S01E01.nfo").exists()
    assert (plan.final_target_dir / f"{plan.show_dir_name} - S01E02.nfo").exists()
    # 验证 episode 文件被复制到 final 目录
    for ep in plan.episodes:
        assert (plan.final_target_dir / ep.target_file.name).exists()
    # 验证 final 目录结构
    assert plan.final_target_dir.exists()
    assert plan.final_target_dir.parent.parent == config.shows_dir


def test_execute_show_write_merges_into_existing_show_root_and_repoints_assets(
    tmp_path: Path,
) -> None:
    config = make_config(tmp_path)
    session_factory = create_session_factory(config)
    source_path = config.downloads_dir / "Show.Title.S01E01.mkv"
    source_path.write_bytes(b"episode-bytes")
    detail = make_show_detail()
    detail = MetadataDetail(**{
        **detail.__dict__,
        "images": MetadataImages(
            poster_url="https://img.test/poster.jpg",
            backdrop_url="https://img.test/backdrop.jpg",
            logo_url="https://img.test/logo.png",
        ),
    })
    episodes = [
        EpisodeTarget(episode=1, season=1, source_file=source_path, target_file=Path("")),
    ]
    client = make_http_client({
        "https://img.test/poster.jpg": httpx.Response(200, content=b"poster"),
        "https://img.test/backdrop.jpg": httpx.Response(200, content=b"backdrop"),
        "https://img.test/logo.png": httpx.Response(200, content=b"logo"),
    })

    with session_factory() as session:
        task = IngestTaskRepository(session).create(
            IngestTaskCreate(
                source_path=str(source_path),
                status="confirmed",
                current_step="confirmed",
                media_type="show",
            )
        )
        plan = build_show_write_plan(
            shows_dir=config.shows_dir,
            episodes=episodes,
            detail=detail,
            task_id=task.id,
        )
        plan.final_target_dir.mkdir(parents=True, exist_ok=True)
        (plan.final_target_dir / "legacy.keep").write_text("keep")

        result = execute_show_write(
            session,
            task_id=task.id,
            detail=detail,
            plan=plan,
            client=client,
        )
        session.commit()

        assets = session.scalars(select(FileAsset).where(FileAsset.task_id == task.id)).all()

    assert result.status == "succeeded"
    final_show_root = plan.final_target_dir.parent
    assert (final_show_root / "tvshow.nfo").exists()
    assert (final_show_root / f"{plan.show_dir_name}-poster.jpg").exists()
    assert (final_show_root / f"{plan.show_dir_name}-fanart.jpg").exists()
    assert (final_show_root / f"{plan.show_dir_name}-clearlogo.png").exists()
    assert (plan.final_target_dir / plan.episodes[0].target_file.name).exists()
    assert (plan.final_target_dir / "legacy.keep").exists()
    assert not (config.shows_dir / ".media-pilot-staging" / task.id).exists()
    assert assets, "expected FileAsset rows for published show"
    assert all(".media-pilot-staging" not in asset.path for asset in assets)
    assert all(Path(asset.path).exists() for asset in assets)


# ── helpers ──

def make_show_detail() -> MetadataDetail:
    return MetadataDetail(
        provider="tmdb",
        provider_id="show:67890",
        media_type="show",
        title="Example Show",
        original_title="Example Original Show",
        year=2026,
        plot="Fake show plot",
        runtime_minutes=None,
        premiered="2026-03-01",
        rating=8.2,
        genres=["Sci-Fi"],
        countries=["US"],
        studios=["Show Studio"],
        credits=MetadataCredits(
            directors=[
                make_show_person(
                    provider_id="200", name="Show Director", role="Director",
                    profile_url="https://example.invalid/show-director",
                    image_url="https://example.invalid/show-director.jpg",
                )
            ],
            actors=[
                make_show_person(
                    provider_id="600", name="Show Actor", role="Main",
                    profile_url="https://example.invalid/show-actor",
                    image_url="https://example.invalid/show-actor.jpg",
                )
            ],
        ),
        external_ids=MetadataExternalIds(imdb_id="tt2026001"),
        images=MetadataImages(
            poster_url="https://example.invalid/poster.jpg",
            backdrop_url="https://example.invalid/backdrop.jpg",
            logo_url="https://example.invalid/logo.png",
        ),
    )


def make_config(root: Path) -> AppConfig:
    config = AppConfig(
        downloads_dir=root / "downloads",
        watch_dir=root / "watch",
        workspace_dir=root / "workspace-root",
        movies_dir=root / "movies",
        shows_dir=root / "shows",
        database_dir=root / "db",
    )
    for directory in (
        config.downloads_dir,
        config.watch_dir,
        config.workspace_dir,
        config.movies_dir,
        config.shows_dir,
        config.database_dir,
    ):
        directory.mkdir(parents=True, exist_ok=True)
    initialize_database(config)
    return config


def make_http_client(routes: dict[str, httpx.Response]) -> httpx.Client:
    def handler(request: httpx.Request) -> httpx.Response:
        return routes.get(str(request.url), httpx.Response(404))

    return httpx.Client(transport=httpx.MockTransport(handler))


def make_show_person(*, provider_id: str, name: str, role: str, profile_url: str, image_url: str):
    from media_pilot.adapters.metadata import MetadataPerson

    return MetadataPerson(
        provider="tmdb",
        provider_id=provider_id,
        name=name,
        role=role,
        profile_url=profile_url,
        image_url=image_url,
    )


# ── same-stem subtitle copy (Task 4) ──────────────────────────


def test_execute_show_write_copies_same_stem_subtitles(
    tmp_path: Path, monkeypatch,
) -> None:
    """每个 episode 的 same-stem 字幕被自动复制到 final 目录, 名称基于 target stem."""
    config = make_config(tmp_path)
    session_factory = create_session_factory(config)
    ep1_path = config.downloads_dir / "Show.S01E01.mkv"
    ep1_path.write_bytes(b"ep1")
    # 同源字幕 — 必须和视频 stem 完全一致
    (config.downloads_dir / "Show.S01E01.srt").write_text("sub1")
    # 另一个语言的同源字幕 (stem 以 video_stem 开头)
    (config.downloads_dir / "Show.S01E01.chs.srt").write_text("chs1")
    # 另一个 episode 的同源字幕 — 不应被本次 episode 携带
    (config.downloads_dir / "Show.S01E02.srt").write_text("other-ep")

    detail = make_show_detail()
    detail = MetadataDetail(**{
        **detail.__dict__,
        "images": MetadataImages(
            poster_url="https://img.test/poster.jpg",
            backdrop_url=None,
            logo_url=None,
        ),
    })
    client = make_http_client({
        "https://img.test/poster.jpg": httpx.Response(200, content=b"poster"),
    })

    with session_factory() as session:
        task = IngestTaskRepository(session).create(
            IngestTaskCreate(
                source_path=str(ep1_path),
                status="confirmed", current_step="confirmed",
                media_type="show",
            )
        )
        plan = build_show_write_plan(
            shows_dir=config.shows_dir,
            episodes=[
                EpisodeTarget(episode=1, season=1,
                              source_file=ep1_path, target_file=Path("")),
            ],
            detail=detail,
            task_id=task.id,
        )
        result = execute_show_write(
            session, task_id=task.id,
            detail=detail, plan=plan, client=client,
        )
        session.commit()

    # 状态 warning (backdrop/logo 缺失) 或 succeeded 都可; 关键是字幕存在
    assert result.status in ("succeeded", "warning")
    # E01 同源字幕全部复制到 final 目录
    final_dir = plan.final_target_dir
    target_stem = plan.show_dir_name + " - S01E01"
    assert (final_dir / f"{target_stem}.srt").exists()
    assert (final_dir / f"{target_stem}.chs.srt").exists()
    # 其它 episode 的字幕不在这里
    assert not any("E02" in p.name for p in final_dir.iterdir() if p.is_file())


def test_execute_show_write_non_same_stem_subtitle_not_carried(
    tmp_path: Path, monkeypatch,
) -> None:
    """非 same-stem 字幕 (e.g. 与视频无关的 srt) 不自动携带, 不阻塞发布."""
    config = make_config(tmp_path)
    session_factory = create_session_factory(config)
    ep1_path = config.downloads_dir / "Show.S01E01.mkv"
    ep1_path.write_bytes(b"ep1")
    # 与视频 stem 不匹配的字幕
    (config.downloads_dir / "OtherShow.srt").write_text("unrelated")

    detail = make_show_detail()
    detail = MetadataDetail(**{
        **detail.__dict__,
        "images": MetadataImages(
            poster_url="https://img.test/poster.jpg",
            backdrop_url=None,
            logo_url=None,
        ),
    })
    client = make_http_client({
        "https://img.test/poster.jpg": httpx.Response(200, content=b"poster"),
    })

    with session_factory() as session:
        task = IngestTaskRepository(session).create(
            IngestTaskCreate(
                source_path=str(ep1_path),
                status="confirmed", current_step="confirmed",
                media_type="show",
            )
        )
        plan = build_show_write_plan(
            shows_dir=config.shows_dir,
            episodes=[
                EpisodeTarget(episode=1, season=1,
                              source_file=ep1_path, target_file=Path("")),
            ],
            detail=detail,
            task_id=task.id,
        )
        result = execute_show_write(
            session, task_id=task.id,
            detail=detail, plan=plan, client=client,
        )
        session.commit()

    # 发布成功 (warning/succeeded), 没有无关字幕被复制
    assert result.status in ("succeeded", "warning")
    final_dir = plan.final_target_dir
    target_stem = plan.show_dir_name + " - S01E01"
    assert not (final_dir / "OtherShow.srt").exists()
    # target_stem.srt 也不存在 (没有 same-stem 字幕可复制)
    assert not (final_dir / f"{target_stem}.srt").exists()


def test_execute_show_write_missing_subtitle_source_warns_but_succeeds(
    tmp_path: Path, monkeypatch,
) -> None:
    """same-stem 字幕源丢失 → warning 但发布成功, 不阻塞."""
    config = make_config(tmp_path)
    session_factory = create_session_factory(config)
    ep1_path = config.downloads_dir / "Show.S01E01.mkv"
    ep1_path.write_bytes(b"ep1")
    # 创建字幕条目但立刻删掉, 模拟源文件丢失
    sub = config.downloads_dir / "Show.S01E01.srt"
    sub.write_text("sub")
    sub.unlink()

    detail = make_show_detail()
    detail = MetadataDetail(**{
        **detail.__dict__,
        "images": MetadataImages(
            poster_url="https://img.test/poster.jpg",
            backdrop_url=None,
            logo_url=None,
        ),
    })
    client = make_http_client({
        "https://img.test/poster.jpg": httpx.Response(200, content=b"poster"),
    })

    with session_factory() as session:
        task = IngestTaskRepository(session).create(
            IngestTaskCreate(
                source_path=str(ep1_path),
                status="confirmed", current_step="confirmed",
                media_type="show",
            )
        )
        plan = build_show_write_plan(
            shows_dir=config.shows_dir,
            episodes=[
                EpisodeTarget(episode=1, season=1,
                              source_file=ep1_path, target_file=Path("")),
            ],
            detail=detail,
            task_id=task.id,
        )
        result = execute_show_write(
            session, task_id=task.id,
            detail=detail, plan=plan, client=client,
        )
        session.commit()

    # 仍然 succeeded 或 warning, 不因字幕丢失失败
    assert result.status in ("succeeded", "warning")
    # 视频文件存在
    final_dir = plan.final_target_dir
    assert any(p.suffix == ".mkv" for p in final_dir.iterdir())


def test_cleanup_show_overwrite_targets_removes_only_current_episode_same_stem_subtitles(
    tmp_path: Path,
) -> None:
    detail = make_show_detail()
    shows_dir = tmp_path / "shows"
    episodes = [
        EpisodeTarget(episode=51, season=1, source_file=tmp_path / "S01E51.mkv", target_file=Path("")),
    ]
    plan = build_show_write_plan(
        shows_dir=shows_dir, episodes=episodes, detail=detail, task_id="task-1",
    )
    plan.final_target_dir.mkdir(parents=True, exist_ok=True)
    current_video = plan.final_target_dir / f"{plan.show_dir_name} - S01E51.mkv"
    current_video.write_bytes(b"video")
    current_nfo = plan.final_target_dir / f"{plan.show_dir_name} - S01E51.nfo"
    current_nfo.write_text("nfo")
    current_lang_sub = plan.final_target_dir / f"{plan.show_dir_name} - S01E51.chs.srt"
    current_lang_sub.write_text("chs")
    current_ass_sub = plan.final_target_dir / f"{plan.show_dir_name} - S01E51.sc.ass"
    current_ass_sub.write_text("ass")
    other_episode_sub = plan.final_target_dir / f"{plan.show_dir_name} - S01E52.chs.srt"
    other_episode_sub.write_text("other")

    _cleanup_show_overwrite_targets(plan)

    assert not current_video.exists()
    assert not current_nfo.exists()
    assert not current_lang_sub.exists()
    assert not current_ass_sub.exists()
    assert other_episode_sub.exists()
